// export const host = "https://funtalkserver.onrender.com";
export const host = "http://localhost:5000";
export const registerRoute = `${host}/api/register`;
export const loginRoute = `${host}/api/login`;
export const allUsersRoute = `${host}/api/auth/allUsers`;
export const sendMessegeRoute = `${host}/api/messeges/addmsg`;
export const getAllMessegesRoutes = `${host}/api/messeges/getmsg`;
export const deleteMessegeRoutes = `${host}/api/messeges/deletemsg`;
export const renameRoute = `${host}/api/auth/updateUsername`;