// export const host = "https://funtalkserver.onrender.com";
export const host = "http://localhost:5000";
export const registerRoute = `${host}/api/register`;
export const loginRoute = `${host}/api/login`;
export const usersRoute = `${host}/api/users`;
export const sendMessegeRoute = `${host}/api/message`;
export const getMessagesRoute = `${host}/api/messages`;
export const deleteMessegeRoutes = `${host}/api/messeges/deletemsg`;
export const renameRoute = `${host}/api/auth/updateUsername`;